apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: $(NAMESPACE_PLACEHOLDER)

resources:
- ../../base

patchesStrategicMerge:
- patch-backup.yaml
- patch-service-monitor.yaml
- patch-ingressroute.yaml
- patch-vault-cert.yaml

configurations:
- kustomizeconfig.yaml

helmCharts:
- name: vault
  version: 0.27.0
  releaseName: $(NAME_PLACEHOLDER)
  repo: https://helm.releases.hashicorp.com
  valuesFile: values.yaml
  namespace: $(NAMESPACE_PLACEHOLDER)
