apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: friday-vault

resources:
# - configmap/
- ../../base

# configMapGenerator:
# - name: friday-vault-values-configmap
#   files:
#   - values.yaml
#   options:
#     disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: friday-vault-values-configmap
    namespace: friday-vault
    fieldPath: data.values.yaml.name
  targets:
  - select:
      kind: ServiceMonitor
    fieldPaths:
    # - metadata.labels.app.kubernetes.io/instance
    - metadata.name
    # - spec.selector.matchLabels.app.kubernetes.io/instance
  # - select:
  #     kind: ConfigMap
  #     name: vault-values-template
  #   fieldPaths:
  #   - data.global.ha.raft.config.retry_join.leader_api_addr

replacements:
- source:
    kind: ConfigMap
    name: friday-vault-values-configmap
    namespace: friday-vault
    fieldPath: data.values.yaml.namespace
  targets:
  - select:
      kind: ServiceMonitor
    fieldPaths:
    - metadata.namespace
    - spec.namespaceSelector.matchNames[*]
  # - select:
  #     kind: ConfigMap
  #     name: vault-values-template
  #   fieldPaths:
  #   - data.global.ha.raft.config.retry_join.leader_api_addr

helmCharts:
- name: vault
  version: 0.27.0
  releaseName: friday2
  repo: https://helm.releases.hashicorp.com
  valuesFile: vault-values-template.yaml  # Adjusted path
  namespace: friday-vault
