apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: friday-vault

resources:
- ../../base

configMapGenerator:
- name: friday-vault-values-configmap
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: friday-vault-values-configmap
    fieldPath: data/name
  targets:
  - select:
      kind: HelmChart
    fieldPaths:
    - releaseName

- source:
    kind: ConfigMap
    name: friday-vault-values-configmap
    fieldPath: data/namespace
  targets:
  - select:
      kind: HelmChart
    fieldPaths:
    - namespace

- source:
    kind: ConfigMap
    name: friday-vault-values-configmap
    fieldPath: data/name
  targets:
  - select:
      kind: ServiceMonitor
    fieldPaths:
    - metadata.labels.app.kubernetes.io/instance
    - metadata.name
    - spec.selector.matchLabels.app.kubernetes.io/instance

- source:
    kind: ConfigMap
    name: friday-vault-values-configmap
    fieldPath: data/namespace
  targets:
  - select:
      kind: ServiceMonitor
    fieldPaths:
    - metadata.namespace
    - spec.namespaceSelector.matchNames[*]

helmCharts:
- name: vault
  version: 0.27.0
  releaseName: $(NAME_PLACEHOLDER)  # Placeholder to be replaced
  repo: https://helm.releases.hashicorp.com
  valuesFile: vault-values-template.yaml
  namespace: $(NAMESPACE_PLACEHOLDER)  # Placeholder to be replaced
