apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: $(NAMESPACE_PLACEHOLDER)

resources:
- ../../base

configMapGenerator:
- name: friday-vault-values-configmap
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: friday-vault-values-configmap
    apiVersion: v1
    fieldRef:
      fieldPath: data/namespace
  targets:
  - select:
      kind: Kustomization
    fieldPaths:
    - spec.namespace

- source:
    name: friday-vault-values-configmap
    field:
      name: name
  targets:
  - select:
      kind: HelmChart
    fieldPaths:
    - spec.releaseName
- source:
    name: friday-vault-values-configmap
    field:
      name: namespace
  targets:
  - select:
      kind: HelmChart
    fieldPaths:
    - spec.namespace

- source:
    name: friday-vault-values-configmap
    field:
      name: namespace
  targets:
  - select:
      kind: ServiceMonitor
    fieldPaths:
    - metadata.namespace
    - spec.namespaceSelector.matchNames[*]

- source:
    name: friday-vault-values-configmap
    field:
      name: name
  targets:
  - select:
      kind: ServiceMonitor
    fieldPaths:
    - metadata.labels.app.kubernetes.io/instance
    - metadata.name
    - spec.selector.matchLabels.app.kubernetes.io/instance

helmCharts:
- name: vault
  version: 0.27.0
  releaseName: $(NAME_PLACEHOLDER)
  repo: https://helm.releases.hashicorp.com
  valuesFile: vault-values.yaml
  namespace: $(NAMESPACE_PLACEHOLDER)

