kind: Kustomization

namespace: $(NAMESPACE_PLACEHOLDER)

resources:
- ../../base

configMapGenerator:
- name: friday-vault-values-configmap
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true

replacements:
- source:
    name: friday-vault-values-configmap
    field:
      name: name
  targets:
  - select:
      kind: HelmChart
    fieldPaths:
    - spec.releaseName
    - spec.valuesFile.data.name

- source:
    name: friday-vault-values-configmap
    field:
      name: namespace
  targets:
  - select:
      kind: HelmChart
    fieldPaths:
    - spec.namespace
    - spec.valuesFile.data.namespace

  - select:
      kind: ServiceMonitor
    fieldPaths:
    - metadata.namespace
    - spec.namespaceSelector.matchNames[*]

  - select:
      kind: "*"
    fieldSpecs:
    - path: data/server/ha/raft/config/retry_join/leader_api_addr
      kind: string

helmCharts:
- name: vault
  version: 0.27.0
  releaseName: $(NAME_PLACEHOLDER)
  repo: https://helm.releases.hashicorp.com
  valuesFile: ../../base/vault-values.yaml
  namespace: $(NAMESPACE_PLACEHOLDER)
