apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: $(NAMESPACE_PLACEHOLDER)

resources:
- ../../base

configMapGenerator:
- name: friday-vault-values-configmap
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true


vars:
- name: NAMESPACE_PLACEHOLDER
  objref:
    kind: ConfigMap
    name: friday-vault-values-configmap
    apiVersion: v1
  fieldref:
    fieldpath: data/namespace

- name: NAME_PLACEHOLDER
  objref:
    kind: ConfigMap
    name: friday-vault-values-configmap
    apiVersion: v1
  fieldref:
    fieldpath: data/name

helmCharts:
- name: vault
  version: 0.27.0
  releaseName: $(NAME_PLACEHOLDER)
  repo: https://helm.releases.hashicorp.com
  valuesFile: vault-values.yaml
  namespace: $(NAMESPACE_PLACEHOLDER)
