aapiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: friday-vault

resources:
- ../../base

configMapGenerator:
- name: friday-vault-values-configmap
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: friday-vault-values-configmap
    fieldPath: data/name
  targets:
  - select:
      kind: ServiceMonitor
    fieldPaths:
    - metadata.labels.app.kubernetes.io/instance
    - metadata.name
    - spec.selector.matchLabels.app.kubernetes.io/instance
  - select:
      kind: ConfigMap
      name: vault-values-template
    fieldPaths:
    - data.global.ha.raft.config.retry_join.leader_api_addr

- source:
    kind: ConfigMap
    name: friday-vault-values-configmap
    fieldPath: data/namespace
  targets:
  - select:
      kind: ServiceMonitor
    fieldPaths:
    - metadata.namespace
    - spec.namespaceSelector.matchNames[*]
  - select:
      kind: ConfigMap
      name: vault-values-template
    fieldPaths:
    - data.global.ha.raft.config.retry_join.leader_api_addr

helmCharts:
- name: vault
  version: 0.27.0
  releaseName: friday
  repo: https://helm.releases.hashicorp.com
  valuesFile: vault-values-template.yaml  # Adjusted path
  namespace: friday-vault
