apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: placeholder-namespace

resources:
- backup.yaml
- service-monitor.yaml
- ingressroute.yaml
- configmap.yaml
- vault-cert.yaml
