global:
  serverTelemetry:
    prometheusOperator: true
  tlsDisable: true
injector:
  enabled: false
server:
  shareProcessNamespace: true
  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
  livenessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true"
    initialDelaySeconds: 60
  logLevel: "debug"
  service:
    enabled: true
    clusterIP: None
  ha:
    enabled: true
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        disable_mlock = true
        listener "tcp" {
          tls_disable = true
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          telemetry {
            unauthenticated_metrics_access = "true"
          }
        }
        telemetry {
          prometheus_retention_time = "30m"
          disable_hostname = true
        }
        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "https://$(NAME_PLACEHOLDER)-vault-0.$(NAME_PLACEHOLDER)-vault-internal.$(NAME_PLACEHOLDER)-vault.svc.cluster.local:8200"
          }
          retry_join {
            leader_api_addr = "https://$(NAME_PLACEHOLDER)-vault-1.$(NAME_PLACEHOLDER)-vault-internal.$(NAME_PLACEHOLDER)-vault.svc.cluster.local:8200"
          }
          retry_join {
            leader_api_addr = "https://$(NAME_PLACEHOLDER)-vault-2.$(NAME_PLACEHOLDER)-vault-internal.$(NAME_PLACEHOLDER)-vault.svc.cluster.local:8200"
          }
        }
        service_registration "kubernetes" {}
  serverTelemetry:
    serviceMonitor:
      enabled: true
